Вёрстка по тестовому заданию
IdPowers/frontend-test pull request #2
Opened 2017-06-17 15:04 UTC by RadikFakhriev

2017-06-18 16:57 UTC, mr-raccoon-dev requested changes
В целом - нужно переделать без flex, убрать медиавыражения (абсолюто не нужные в данном случае), сделать "резину", и исправить js

2017-06-18 16:57 UTC, mr-raccoon-dev commented on client/src/blocks/button/button.pug
> +  +b.BUTTON.regular-button(id=obj.id || false)= obj.text || ''
Если блок называется `regular-button`, то и сам файл должен называться аналогично. Соответственно и сам миксин.

2017-06-18 16:57 UTC, mr-raccoon-dev commented on client/src/blocks/button/button.styl
> +$bl = "regular-button"
Название блока не соответствует названию файла. То же самое как и в случае с `pug`-файлом.

2017-06-18 16:57 UTC, mr-raccoon-dev commented on client/src/blocks/framed-select/framed-select.styl
> +$bl = 'select2-container'
Снова `$bl` не соответствует названию блока.
Лучше было бы конкретную реализацию положить в обертку названную как раз `framed-select` и в ней уже инициализировать `select2` с параметром `dropdownParent`. 
Соответственно стилизация была реализована в виде `.{$bl} > .select2-container`.
Либо же стилизовать можно было просто темой.

2017-06-18 16:57 UTC, mr-raccoon-dev commented on client/src/blocks/framed-select/framed-select.styl
> +  & .select2-selection--single
(не ошибка) - `&` можно опускать

2017-06-18 16:57 UTC, mr-raccoon-dev commented on client/src/blocks/product-preview/product-preview.js
> +import $ from 'jquery';
Глобальные импорты следует делать первыми.

2017-06-18 16:57 UTC, mr-raccoon-dev commented on client/src/blocks/framed-select/framed-select.pug
> +  +b.SELECT.framed-select(id=obj.id || false, data-width=obj.width || '100%')
`id` лучше было бы реализовать через `attributes`, что позволит использовать базовую запись вида `+FramedSelect#id`

2017-06-18 16:57 UTC, mr-raccoon-dev commented on client/src/blocks/product-preview/product-preview.pug
> +          +e.brand NIKE
Не нужно использовать Caps в разметке

2017-06-18 16:57 UTC, mr-raccoon-dev commented on client/src/blocks/product-preview/product-preview.pug
> +            +e.LABEL
Нужно добавить название элемента, чтобы оставлять `CSS` максимально плоским (без каскадной привязки) и сохранять наглядность кода

2017-06-18 16:57 UTC, mr-raccoon-dev commented on client/src/blocks/product-preview/product-preview.pug
> +            +e.LABEL
Опять-таки нужно добавить название элемента (теряется наглядность)

2017-06-18 16:57 UTC, mr-raccoon-dev commented on client/src/blocks/product-preview/product-preview.pug
> +          +e.LABEL Size charts
Название элемента

2017-06-18 16:57 UTC, mr-raccoon-dev commented on client/src/blocks/product-preview/product-preview.styl
> +    input[name="colors"]
Не нужно привязываться к реализации элементов форм к атрибутам.

2017-06-18 16:57 UTC, mr-raccoon-dev commented on client/src/blocks/product-preview/product-preview.styl
> +.select2-container + .regular-button
Блоки не знают ничего друг о друге. Кнопке нужно смиксовать классами с этим блоком (`.{$bl}__button` или любое другое название)

2017-06-18 16:57 UTC, mr-raccoon-dev commented on client/src/blocks/product-preview/product-preview.styl
> +    font-size 23px
Нужно явно указать `line-height` у шрифта

2017-06-18 16:57 UTC, mr-raccoon-dev commented on client/src/blocks/product-story/product-story.pug
> +          +e.title STORY
Не нужно использовать `Caps` в разметке (если только это не как часть контентного текста).

2017-06-18 16:57 UTC, mr-raccoon-dev commented on client/src/blocks/product-story/product-story.pug
> +          +e.big-title NIKE AIR MAX ORIGINS
Название не несет семантической нагрузки. Если уж и называть `title`, то с модификатором - `+e.title_big`

2017-06-18 16:57 UTC, mr-raccoon-dev commented on client/src/blocks/product-story/product-story.pug
> +          +e.benefit Layered textile/synthetic upper
Лучше сделать немаркированным списком все `benefit+detail`

2017-06-18 16:57 UTC, mr-raccoon-dev commented on client/src/blocks/product-story/product-story.pug
> +        +e.product-image(src=require('assets/sneakers-pair.png'))
В данном случае лучше реализовать фоном. Но не критично

2017-06-18 16:57 UTC, mr-raccoon-dev commented on client/src/blocks/product-story/product-story.pug
> +        +e.panel
Вообще, вся данная панель практически эдентична той что была в `product-preview` - лучше это вынести в отдельный миксин, разделяя их модификаторами.
Так же разный контент - список картинок в `product-preview` и одна в данном случае. Это опять же можно реализовать в миксине.

2017-06-18 16:57 UTC, mr-raccoon-dev commented on client/src/blocks/product-story/product-story.pug
> +              +e.LABEL
Нет названия элемента

2017-06-18 16:57 UTC, mr-raccoon-dev commented on client/src/blocks/product-story/product-story.styl
> +    display flex
`display flex` отпадает из-за требований к браузерам - IE+
Соответственно по всему коду нужно переделать

2017-06-18 16:57 UTC, mr-raccoon-dev commented on client/src/blocks/product-story/product-story.styl
> +    & span:first-child
Раз используются `float` то контейнеру нужно сделать распорку, чтобы убрать схлопывание

2017-06-18 16:57 UTC, mr-raccoon-dev commented on client/src/blocks/product-story/product-story.styl
> +  &__panel
Нужно ограничить по максимально допустимой ширине

2017-06-18 16:57 UTC, mr-raccon commented on client/src/blocks/footer/footer.styl
> -    width 790px
<img width="1260" alt="2017-06-18 18 58 46" src="https://user-images.githubusercontent.com/10694279/27262086-315275f8-5458-11e7-8e8b-d0faa0da8216.png">
Вот яркий пример почему не нужно убирать явную ширину, притом при миксе с флоатами.
Совершенно не понимаю решения убрать ширину и добавить `float`.

2017-06-18 16:57 UTC, mr-raccon commented on client/src/blocks/footer/footer.styl
> +@media (max-width: 1280px)
Вообще в ТЗ речь шла о "резиновой"(rubber) верстке - которая строится на процентном соотношении - для чего здесь медиавыражения я не понимаю.
Все можно было решить через `calc` блока sitemap

2017-06-18 16:57 UTC, mr-raccon commented on client/src/blocks/page/page.styl
> +@media (max-width: 1280px)
Нужно было выставить без медиавырежия, заменив изначальное значение

2017-06-18 16:57 UTC, mr-raccon commented on client/src/blocks/product-preview/product-preview.styl
> +    display table-cell
Окей, но все-таки желательно чтобы `display: table-cell` лежал в `display: table`

2017-06-18 16:57 UTC, mr-raccon commented on client/src/blocks/product-social/product-social.styl
> +      & img
1 - у `img` есть класс
2 - медиа выражения лучше писать под элементами 
3 - медиа выражение в данном случае лишнее, так как можно было обойтись 
```
&__post-image
  max-width 100%
  height auto
```

2017-06-18 16:57 UTC, mr-raccon commented on client/src/blocks/product-story/product-story.styl
> +      line-height 550px
Достаточно спорное решение, которое повлечет рефакторинг в случае создания адаптива. Снова повторюсь, что можно было вывести фоном данное изображение.

2017-06-18 16:57 UTC, mr-raccon commented on client/package.json
> +    "semantic-ui-sidebar": "^2.2.10"
Не желательно подключать целый плагин ради такой мелочи (плюс затемнение не соответствует макету)

2017-06-18 16:57 UTC, mr-raccon commented on client/src/blocks/cart-entry/cart-entry.styl
> +  display table-row
можно было просто `display: table`

2017-06-18 16:57 UTC, mr-raccon commented on client/src/blocks/cart-sidebar/cart-sidebar.js
> +$('.header__cart').on('click', () => {
Не надо использовать стрелочную функцию в обработчиках, так как теряется контекст - `this`

2017-06-18 16:57 UTC, mr-raccon commented on client/src/blocks/cart-sidebar/cart-sidebar.pug
> +            image: require('assets/nike-in-cart.png'),
не то изображение

2017-06-18 16:57 UTC, mr-raccon commented on client/src/blocks/cart-sidebar/cart-sidebar.styl
> +  display flex
Флексы не используются

2017-06-18 16:57 UTC, mr-raccon commented on client/src/blocks/cart-sidebar/cart-sidebar.styl
> +    clear both
распорку для флоатов нужно делать на контейнере в котором флоаты, т.е. `__resume`

2017-06-18 16:57 UTC, mr-raccon commented on client/src/blocks/cart-sidebar/cart-sidebar.styl
> +.flex-input
Должно быть во `light-input` как модификатор, либо как элемент данного блока

2017-06-18 16:57 UTC, mr-raccon commented on client/src/pages/index/index.styl
> +@import '../../../node_modules/semantic-ui-sidebar/sidebar.min.css';
лучше переместить в `CartSidebar`

2017-06-18 16:57 UTC, mr-raccon commented on client/src/blocks/cart-sidebar/cart-sidebar.js
> +  $currentAmount.text(parseInt($currentAmount.text(), 10) + 1);
лучше использовать data-аттрибуты для данных

2017-06-18 16:57 UTC, mr-raccon commented on client/src/blocks/cart-sidebar/cart-sidebar.js
> +  $currentAmount.text(parseInt($currentAmount.text(), 10) + 1);
Лучше создать отдельную сущность под корзину, у которой будет состояние в котором `currentAmount` и тд, а также API (методы) для изменения в нем нужных данных.
Это добавит наглядности и модульности кода.

2017-06-18 16:57 UTC, mr-raccon commented on client/src/blocks/cart-sidebar/cart-sidebar.js
> +    $currentAmount.text(productAmount - 1);
У самих элементов счетчик меняется, но нет расчета `subtotal`

2017-06-18 16:57 UTC, mr-raccon commented on client/src/blocks/cart-sidebar/cart-sidebar.js
> +  $('#delete-dialog').modal('hide');
Попап при прокрутке страницы показывается не корректно - это самый верх браузера
Сюда же отнесу очень маленькие размеры кнопок `+` и `-`
<img width="789" alt="2017-06-18 19 41 53" src="https://user-images.githubusercontent.com/10694279/27262379-38f01350-545e-11e7-8fc3-a683096ed1cb.png">

2017-06-18 16:57 UTC, mr-raccon commented on client/src/blocks/cart-sidebar/cart-sidebar.pug
> +  -      image: require('assets/nike-in-cart.png'),
Не критично - не верно изображение согласно макету

2017-06-18 16:57 UTC, mr-raccon commented on client/src/blocks/cart-sidebar/cart-sidebar.pug
> +  -var total = prices.reduce(function(sum, current) {
В шаблонах - отлично, нужно еще в js реализовать

2017-06-18 16:57 UTC, mr-raccon commented on client/src/blocks/delete-dialog/delete-dialog.pug
> +  +b.modal.fade#delete-dialog(role="dialog", aria-hidden="true")
Название блока не соответствует названию миксина и файла

2017-06-18 16:57 UTC, mr-raccon commented on client/src/blocks/delete-dialog/delete-dialog.pug
> +    +b.modal-dialog.modal-sm
Причина разделения на несколько блоков? Все можно и даже желательно было сделать элементами

2017-06-18 16:57 UTC, mr-raccon commented on client/src/blocks/footer/footer.pug
> +    script(src="//yastatic.net/es5-shims/0.0.2/es5-shims.min.js")
Нет, шаринг нужно реализовать на сверстанных элементах без `ya-share`

2017-06-18 16:57 UTC, mr-raccon commented on client/src/blocks/light-select/light-select.styl
> +$bl = 'select2-container'
`$bl` - это название блока (light-select) в данном случаи

2017-06-18 16:57 UTC, mr-raccon commented on client/src/blocks/product-preview/product-preview.styl
> +    display inline-flex
И снова повторюсь - флексы не используются

2017-06-18 16:57 UTC, mr-raccon commented on client/src/blocks/checkbox/checkbox.styl
> +.control
Отсутствует `$bl`
Плюс если блок - `checkbox` то и стили называться должны `checkbox`, а не `control`
Либо же наоборот - файл назвать по-другому

2017-06-18 16:57 UTC, mr-raccon commented on client/src/blocks/product-preview/product-preview.styl
> +  font-weight 500
Блок нужно отцентровать, иначе слишком много пустого пространства справа

2017-06-18 17:06 UTC, mr-raccon commented
@RadikFakhriev, еще обнови свой репозиторий из основного

2017-06-23 12:00 UTC, RadikFakhriev commented
@mr-raccon, а когда результат проверки сообщите?

2017-06-26 17:51 UTC, mr-raccon commented
@RadikFakhriev, завтра, нет возможности оперативно проверить к сожалению (

2017-06-27 20:25 UTC, mr-raccon commented
@RadikFakhriev 
Футер не резиновый, и соответственно разваливается при ресайзе
В шаринге в соц сети - отсутствует мета информация (заголовок, описание)

2017-06-27 20:25 UTC, mr-raccoon-dev requested changes
Футер не резиновый, и соответственно разваливается при ресайзе
В шаринге в соц сети - отсутствует мета информация (заголовок, описание)

2017-06-27 20:25 UTC, mr-raccon commented on client/src/blocks/cart-sidebar/CartModel.js
> +    const idx = this.products.findIndex((elem) => {
получение текущего продукта можно было сделать отдельным методом, чтобы не дублироваться

2017-06-27 20:25 UTC, mr-raccon commented on client/src/blocks/cart-sidebar/CartModel.js
> +    this.products = this.products.filter((item) => {
не критично, но лучше было бы удалять через `splice` чтобы не "гонять" массив каждый раз

2017-06-28 09:05 UTC, RadikFakhriev commented
@mr-raccon, Обновил PR

2017-06-29 15:37 UTC, mr-raccoon-dev approved these changes

2017-06-29 15:37 UTC, mr-raccon commented on client/src/blocks/cart-sidebar/CartModel.js
> +    }
лучше так - читабельнее
```
let index = this.products.findIndex(item => item.id === productId);
if (index) {
this.products.splice(index, 1);
}
```

2017-06-29 15:37 UTC, merged